#include <stdio.h>
#include "lib_hmgen.h"

#define HMGEN_MODULE "Export"

static int write_pnm_header(FILE *fp, unsigned int n,
                            unsigned int w, unsigned int h) {
    const char *gen_by = "Generated by hmgen";

    if (fprintf(fp, "P%i\n# %s\n%i %i\n255\n", n, gen_by, w, h) < 0 )
        return 0;

    return 1;
}

unsigned int hmg_export_pgm(const char *filename, unsigned char *map,
                            unsigned int width, unsigned int height) {
    FILE *fp;
    unsigned int y;

    fp = fopen(filename, "wb");

    if (!fp)
        return 0;

    if (!write_pnm_header(fp, 5, width, height))
        goto err_out;

    for (y=0; y<height; y++) {
        progress_meter(y*100.0/height);
        if (fwrite(map+y*width, width, 1, fp) != 1)
            goto err_out;
    }

    progress_meter(-1);

    return !fclose(fp);

err_out:
    fclose(fp);
    progress_meter(-1);
    return 0;
}

unsigned int hmg_export_ppm(const char *filename, unsigned char *map,
                            unsigned int width, unsigned int height) {
    FILE *fp;
    unsigned int x, y;

    fp = fopen(filename, "wb");

    if (!fp)
        return 0;

    if (!write_pnm_header(fp, 6, width, height))
        goto err_out;

    for (y=0; y<height; y++) {
        progress_meter(y*100.0/height);
        for (x=0; x<width; x++) {
            if (fwrite(hmg_colormap[map[y*width+x]], 1, 3, fp) != 3)
                goto err_out;
        }
    }

    progress_meter(-1);

    return !fclose(fp);

err_out:
    fclose(fp);
    progress_meter(-1);
    return 0;
}

