# Make is obsolete ;)

all:
	@echo "This project does not use make. Use ./build.sh instead."
	@echo "Type ./build.sh --help for details."

clean:
	@./build.sh clean

distclean:
	@./build.sh distclean
